FROM golang:1.24.10-bookworm AS builder

WORKDIR /src

# download dependencies
COPY go.mod go.sum ./
RUN go mod download && go mod verify

# build and install model-hub executable
COPY . .
RUN go build -ldflags "-s -w" -o /model-hub

FROM python:3.14.1-bookworm
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends python3.10 python3-pip sudo curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /bin
COPY --from=builder /model-hub /bin/model-hub
COPY ./worker.py /bin/worker.py
COPY ./requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt && rm /tmp/requirements.txt

ENV CONFIG_PATH="/etc/config.yaml"
ENV SERVER_PORT="8080"
ENV METRICS_DISPLAY_FREQUENCY="30"
ENV WORKERS_LOADING_STRATEGY="parallel"
ENV API_KEY=""
ENV DEBUG=0

ENTRYPOINT ["model-hub"]
