FROM golang:1.21.4-bullseye

WORKDIR /src

# download dependencies
COPY go.mod go.sum ./
RUN go mod download && go mod verify

# build and install model-hub executable
COPY . .
RUN go build -ldflags "-s -w" -o /model-hub

FROM python:3.10.11-bullseye
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends sudo curl
RUN pip install --no-cache-dir requests==2.29.0

WORKDIR /bin
COPY --from=0 /model-hub /bin/model-hub
COPY ./worker.py /bin/worker.py

ENV CONFIG_PATH="/etc/config.yaml"
ENV SERVER_PORT="8080"
ENV METRICS_DISPLAY_FREQUENCY="30"
ENV WORKERS_LOADING_STRATEGY="parallel"


ENTRYPOINT ["model-hub"]
